name: For JMDKH

on:
  push:
  workflow_dispatch:
jobs:
  BuildBase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: token
          password: ${{ secrets.TOKEN }}
      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile2
          platforms: linux/amd64
          push: true
          tags: ghcr.io/tonmoyislam250/alpinedocker:jmdkh2
